//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APM_of_accounting_of_academic_performance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int id_attachment { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_sudject { get; set; }
    
        public virtual Sudjects Sudjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
