//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APM_of_accounting_of_academic_performance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum_in_the_specialtys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curriculum_in_the_specialtys()
        {
            this.Loads = new HashSet<Loads>();
        }
    
        public int id_curriculum_in_the_specialty { get; set; }
        public int id_sudject { get; set; }
        public int id_specialty { get; set; }
        public int all_hours { get; set; }
        public int sudject_hours_theory { get; set; }
        public int sudject_hours_practice { get; set; }
        public int sudject_hours_course_design { get; set; }
        public int semester_numbers { get; set; }
        public int year_of_study { get; set; }
        public string code { get; set; }
    
        public virtual Specialtys Specialtys { get; set; }
        public virtual Sudjects Sudjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loads> Loads { get; set; }
    }
}
