//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APM_of_accounting_of_academic_performance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loads
    {
        public int id_load { get; set; }
        public int id_teacher { get; set; }
        public int id_group { get; set; }
        public int id_curriculum_in_the_specialty { get; set; }
        public System.DateTime date { get; set; }
        public int loud_hours { get; set; }
        public int id_type_of_clock { get; set; }
    
        public virtual Curriculum_in_the_specialtys Curriculum_in_the_specialtys { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Type_of_clocks Type_of_clocks { get; set; }
    }
}
